// <auto-generated />
using System;
using ClaimsModule.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClaimsModule.Persistence.Migrations
{
    [DbContext(typeof(ClaimsDbContext))]
    [Migration("20260528110822_AddClaimSeedData")]
    partial class AddClaimSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClaimsModule.Domain.Entities.CauseOfLossCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PerilCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UserCreated")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserModified")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CauseOfLossCodes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11000000-0000-0000-0000-000000000001"),
                            Code = "COL-FIRE",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Fire",
                            OrganisationId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PerilCategory = "Property",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("11000000-0000-0000-0000-000000000002"),
                            Code = "COL-FLOOD",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Flood",
                            OrganisationId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PerilCategory = "Weather",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("11000000-0000-0000-0000-000000000003"),
                            Code = "COL-THEFT",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Theft",
                            OrganisationId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PerilCategory = "Crime",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("11000000-0000-0000-0000-000000000004"),
                            Code = "COL-VEH-COL",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Vehicle Collision",
                            OrganisationId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PerilCategory = "Auto",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("11000000-0000-0000-0000-000000000005"),
                            Code = "COL-VEH-COMP",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Vehicle Comprehensive",
                            OrganisationId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PerilCategory = "Auto",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("11000000-0000-0000-0000-000000000006"),
                            Code = "COL-LIAB",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Third Party Liability",
                            OrganisationId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PerilCategory = "Liability",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("11000000-0000-0000-0000-000000000007"),
                            Code = "COL-EQUIP",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Equipment Breakdown",
                            OrganisationId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PerilCategory = "Equipment",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = new Guid("11000000-0000-0000-0000-000000000008"),
                            Code = "COL-WIND",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Wind / Storm",
                            OrganisationId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PerilCategory = "Weather",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = new Guid("11000000-0000-0000-0000-000000000009"),
                            Code = "COL-INJURY",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bodily Injury",
                            OrganisationId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PerilCategory = "Liability",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = new Guid("11000000-0000-0000-0000-000000000010"),
                            Code = "COL-OTHER",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Other / Unknown",
                            OrganisationId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PerilCategory = "General",
                            SortOrder = 10
                        });
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.Claim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid?>("AssignedHandlerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClaimNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClientName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ClosureReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("ManagerOverrideFlag")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PolicyNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("ReportedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVer")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Severity")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UserCreated")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserModified")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClaimNumber", "OrganisationId")
                        .IsUnique();

                    b.ToTable("Claims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33000000-0000-0000-0000-000000000001"),
                            ClaimNumber = "CLM-2025-0000001",
                            ClientName = "Harborview Properties Inc",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 20, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            ManagerOverrideFlag = false,
                            OrganisationId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PolicyId = new Guid("22000000-0000-0000-0000-000000000002"),
                            PolicyNumber = "POL-2024-001002",
                            ReportedDate = new DateTimeOffset(new DateTime(2025, 1, 20, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RowVer = new byte[0],
                            Status = "Draft"
                        },
                        new
                        {
                            Id = new Guid("33000000-0000-0000-0000-000000000002"),
                            ClaimNumber = "CLM-2025-0000002",
                            ClientName = "Meridian Transport LLC",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 2, 10, 11, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            ManagerOverrideFlag = false,
                            OrganisationId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PolicyId = new Guid("22000000-0000-0000-0000-000000000001"),
                            PolicyNumber = "POL-2024-001001",
                            ReportedDate = new DateTimeOffset(new DateTime(2025, 2, 10, 11, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RowVer = new byte[0],
                            Status = "Open"
                        },
                        new
                        {
                            Id = new Guid("33000000-0000-0000-0000-000000000003"),
                            ClaimNumber = "CLM-2025-0000003",
                            ClientName = "Stanton Medical Group",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 3, 5, 14, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            ManagerOverrideFlag = false,
                            OrganisationId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PolicyId = new Guid("22000000-0000-0000-0000-000000000004"),
                            PolicyNumber = "POL-2025-002002",
                            ReportedDate = new DateTimeOffset(new DateTime(2025, 3, 5, 14, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RowVer = new byte[0],
                            Status = "UnderInvestigation"
                        },
                        new
                        {
                            Id = new Guid("33000000-0000-0000-0000-000000000004"),
                            ClaimNumber = "CLM-2025-0000004",
                            ClientName = "Coastal Builders Group",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 11, 15, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            ManagerOverrideFlag = false,
                            OrganisationId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PolicyId = new Guid("22000000-0000-0000-0000-000000000003"),
                            PolicyNumber = "POL-2025-002001",
                            ReportedDate = new DateTimeOffset(new DateTime(2024, 11, 15, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RowVer = new byte[0],
                            Status = "PendingPayment"
                        },
                        new
                        {
                            Id = new Guid("33000000-0000-0000-0000-000000000005"),
                            ClaimNumber = "CLM-2025-0000005",
                            ClientName = "Meridian Transport LLC",
                            ClosedAt = new DateTimeOffset(new DateTime(2025, 1, 10, 15, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ClosureReason = "All parties settled. Reserves reconciled.",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 8, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            ManagerOverrideFlag = false,
                            OrganisationId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PolicyId = new Guid("22000000-0000-0000-0000-000000000001"),
                            PolicyNumber = "POL-2024-001001",
                            ReportedDate = new DateTimeOffset(new DateTime(2024, 8, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RowVer = new byte[0],
                            Status = "Closed"
                        },
                        new
                        {
                            Id = new Guid("33000000-0000-0000-0000-000000000006"),
                            ClaimNumber = "CLM-2025-0000006",
                            ClientName = "Harborview Properties Inc",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 4, 3, 16, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            ManagerOverrideFlag = false,
                            OrganisationId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PolicyId = new Guid("22000000-0000-0000-0000-000000000002"),
                            PolicyNumber = "POL-2024-001002",
                            ReportedDate = new DateTimeOffset(new DateTime(2025, 4, 3, 16, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RowVer = new byte[0],
                            Status = "Withdrawn"
                        });
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UserCreated")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserModified")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId", "CreatedAt");

                    b.ToTable("ClaimAuditLogs", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UploadedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserCreated")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserModified")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimDocuments", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimParty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PartyRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PartyType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UserCreated")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserModified")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimParties", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("55000000-0000-0000-0000-000000000001"),
                            ClaimId = new Guid("33000000-0000-0000-0000-000000000001"),
                            CompanyName = "Harborview Properties Inc",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 20, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "claims@harborview.ua",
                            IsActive = true,
                            IsDeleted = false,
                            OrganisationId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PartyRole = "Insured",
                            PartyType = "Company",
                            Phone = "+380442001122"
                        },
                        new
                        {
                            Id = new Guid("55000000-0000-0000-0000-000000000002"),
                            ClaimId = new Guid("33000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 2, 10, 11, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "o.kovalenko@meridian.ua",
                            FirstName = "Oleksandr",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Kovalenko",
                            OrganisationId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PartyRole = "Claimant",
                            PartyType = "Person",
                            Phone = "+380501234567"
                        },
                        new
                        {
                            Id = new Guid("55000000-0000-0000-0000-000000000003"),
                            ClaimId = new Guid("33000000-0000-0000-0000-000000000003"),
                            CompanyName = "Stanton Medical Group",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 3, 5, 14, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "legal@stanton.ua",
                            IsActive = true,
                            IsDeleted = false,
                            OrganisationId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PartyRole = "Claimant",
                            PartyType = "Company",
                            Phone = "+380487654321"
                        },
                        new
                        {
                            Id = new Guid("55000000-0000-0000-0000-000000000007"),
                            ClaimId = new Guid("33000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 3, 5, 14, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Natalia",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Sydorenko",
                            OrganisationId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PartyRole = "Witness",
                            PartyType = "Person",
                            Phone = "+380509876543"
                        },
                        new
                        {
                            Id = new Guid("55000000-0000-0000-0000-000000000004"),
                            ClaimId = new Guid("33000000-0000-0000-0000-000000000004"),
                            CompanyName = "Coastal Builders Group",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 11, 15, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "insurance@coastal.ua",
                            IsActive = true,
                            IsDeleted = false,
                            OrganisationId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PartyRole = "Claimant",
                            PartyType = "Company",
                            Phone = "+380661112233"
                        },
                        new
                        {
                            Id = new Guid("55000000-0000-0000-0000-000000000005"),
                            ClaimId = new Guid("33000000-0000-0000-0000-000000000005"),
                            CompanyName = "Meridian Transport LLC",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 8, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "claims@meridian.ua",
                            IsActive = true,
                            IsDeleted = false,
                            OrganisationId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PartyRole = "Claimant",
                            PartyType = "Company",
                            Phone = "+380991234567"
                        },
                        new
                        {
                            Id = new Guid("55000000-0000-0000-0000-000000000006"),
                            ClaimId = new Guid("33000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 4, 3, 16, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "v.bondarenko@gmail.com",
                            FirstName = "Viktor",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Bondarenko",
                            OrganisationId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PartyRole = "Claimant",
                            PartyType = "Person",
                            Phone = "+380733332211"
                        });
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimReserveComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("CurrentAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVer")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UserCreated")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserModified")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimReserveComponents", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimRiskObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("AssetDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AssetReference")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DamageDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UserCreated")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserModified")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimRiskObjects", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.LossEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("CauseOfLossCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("EstimatedLossAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LossDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LossDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LossLocation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PoliceReportNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("ReportDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UserCreated")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserModified")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId")
                        .IsUnique();

                    b.ToTable("LossEvents", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("44000000-0000-0000-0000-000000000001"),
                            CauseOfLossCode = "COL-FIRE",
                            ClaimId = new Guid("33000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 20, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EstimatedLossAmount = 45000m,
                            IsDeleted = false,
                            LossDate = new DateTimeOffset(new DateTime(2025, 1, 18, 14, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LossDescription = "Electrical fire originated in server room causing damage to equipment and partial structural damage to the building.",
                            LossLocation = "Kyiv, Khreshchatyk 1, Building B",
                            OrganisationId = new Guid("00000000-0000-0000-0000-000000000001"),
                            ReportDate = new DateTimeOffset(new DateTime(2025, 1, 20, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("44000000-0000-0000-0000-000000000002"),
                            CauseOfLossCode = "COL-VEH-COL",
                            ClaimId = new Guid("33000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 2, 10, 11, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EstimatedLossAmount = 18500m,
                            IsDeleted = false,
                            LossDate = new DateTimeOffset(new DateTime(2025, 2, 8, 10, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LossDescription = "Head-on collision at intersection resulted in significant front-end damage to company vehicle and minor injuries to driver.",
                            LossLocation = "Lviv, Svobody Ave 12",
                            OrganisationId = new Guid("00000000-0000-0000-0000-000000000001"),
                            ReportDate = new DateTimeOffset(new DateTime(2025, 2, 10, 11, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("44000000-0000-0000-0000-000000000003"),
                            CauseOfLossCode = "COL-THEFT",
                            ClaimId = new Guid("33000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 3, 5, 14, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EstimatedLossAmount = 120000m,
                            IsDeleted = false,
                            LossDate = new DateTimeOffset(new DateTime(2025, 3, 3, 2, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LossDescription = "Pharmaceutical storage area broken into overnight. Multiple controlled substance cabinets forced open. Police investigation ongoing.",
                            LossLocation = "Odesa, Derybasivska 5, Medical Center",
                            OrganisationId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PoliceReportNumber = "OD-2025-004421",
                            ReportDate = new DateTimeOffset(new DateTime(2025, 3, 5, 14, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("44000000-0000-0000-0000-000000000004"),
                            CauseOfLossCode = "COL-FLOOD",
                            ClaimId = new Guid("33000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 11, 15, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EstimatedLossAmount = 87000m,
                            IsDeleted = false,
                            LossDate = new DateTimeOffset(new DateTime(2024, 11, 12, 6, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LossDescription = "Heavy rainfall caused flash flooding in construction site basement. Equipment submerged, foundation work delayed three weeks.",
                            LossLocation = "Dnipro, Soborna 8, Construction Site",
                            OrganisationId = new Guid("00000000-0000-0000-0000-000000000001"),
                            ReportDate = new DateTimeOffset(new DateTime(2024, 11, 15, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("44000000-0000-0000-0000-000000000005"),
                            CauseOfLossCode = "COL-WIND",
                            ClaimId = new Guid("33000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 8, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EstimatedLossAmount = 32000m,
                            IsDeleted = false,
                            LossDate = new DateTimeOffset(new DateTime(2024, 7, 28, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LossDescription = "Severe wind storm damaged roof of cargo warehouse causing water ingress. Cargo contents partially destroyed.",
                            LossLocation = "Kharkiv, Industrial Zone, Warehouse 14",
                            OrganisationId = new Guid("00000000-0000-0000-0000-000000000001"),
                            ReportDate = new DateTimeOffset(new DateTime(2024, 8, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("44000000-0000-0000-0000-000000000006"),
                            CauseOfLossCode = "COL-INJURY",
                            ClaimId = new Guid("33000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 4, 3, 16, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EstimatedLossAmount = 15000m,
                            IsDeleted = false,
                            LossDate = new DateTimeOffset(new DateTime(2025, 4, 1, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LossDescription = "Third party slip and fall incident in office lobby. Claimant later withdrew citing pre-existing medical condition.",
                            LossLocation = "Kyiv, Business Center, Entrance Hall",
                            OrganisationId = new Guid("00000000-0000-0000-0000-000000000001"),
                            ReportDate = new DateTimeOffset(new DateTime(2025, 4, 3, 16, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.Policy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CoverageTypes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UserCreated")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserModified")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PolicyNumber")
                        .IsUnique();

                    b.ToTable("Policies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22000000-0000-0000-0000-000000000001"),
                            ClientName = "Meridian Transport LLC",
                            CoverageTypes = "Vehicle,Cargo",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EffectiveDate = new DateOnly(2024, 1, 1),
                            ExpirationDate = new DateOnly(2026, 12, 31),
                            IsDeleted = false,
                            OrganisationId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PolicyNumber = "POL-2024-001001",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22000000-0000-0000-0000-000000000002"),
                            ClientName = "Harborview Properties Inc",
                            CoverageTypes = "Property,Liability",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EffectiveDate = new DateOnly(2024, 6, 1),
                            ExpirationDate = new DateOnly(2026, 5, 31),
                            IsDeleted = false,
                            OrganisationId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PolicyNumber = "POL-2024-001002",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22000000-0000-0000-0000-000000000003"),
                            ClientName = "Coastal Builders Group",
                            CoverageTypes = "Property,Equipment",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EffectiveDate = new DateOnly(2025, 3, 1),
                            ExpirationDate = new DateOnly(2027, 2, 28),
                            IsDeleted = false,
                            OrganisationId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PolicyNumber = "POL-2025-002001",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22000000-0000-0000-0000-000000000004"),
                            ClientName = "Stanton Medical Group",
                            CoverageTypes = "Liability,Vehicle",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EffectiveDate = new DateOnly(2025, 1, 1),
                            ExpirationDate = new DateOnly(2026, 12, 31),
                            IsDeleted = false,
                            OrganisationId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PolicyNumber = "POL-2025-002002",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22000000-0000-0000-0000-000000000005"),
                            ClientName = "Archived Corp",
                            CoverageTypes = "Property",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EffectiveDate = new DateOnly(2020, 1, 1),
                            ExpirationDate = new DateOnly(2021, 12, 31),
                            IsDeleted = false,
                            OrganisationId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PolicyNumber = "POL-2023-000099",
                            Status = "Expired"
                        });
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ReserveHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangeReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ChangeSequence")
                        .HasColumnType("int");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("NewBalance")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PostingJobId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PostingStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PreviousBalance")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("RejectedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ReserveComponentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SubmittedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UserCreated")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserModified")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReserveComponentId");

                    b.ToTable("ReserveHistories", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Persistence.ClaimNumberSequence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("LastSequence")
                        .HasColumnType("int");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId", "Year")
                        .IsUnique();

                    b.ToTable("ClaimNumberSequences", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimDocument", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Entities.Claim", null)
                        .WithMany("Documents")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimParty", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Entities.Claim", null)
                        .WithMany("Parties")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimReserveComponent", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Entities.Claim", null)
                        .WithMany("ReserveComponents")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimRiskObject", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Entities.Claim", null)
                        .WithMany("RiskObjects")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.LossEvent", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Entities.Claim", null)
                        .WithOne("LossEvent")
                        .HasForeignKey("ClaimsModule.Domain.Entities.LossEvent", "ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ReserveHistory", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Entities.ClaimReserveComponent", "ReserveComponent")
                        .WithMany("History")
                        .HasForeignKey("ReserveComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReserveComponent");
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.Claim", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("LossEvent");

                    b.Navigation("Parties");

                    b.Navigation("ReserveComponents");

                    b.Navigation("RiskObjects");
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimReserveComponent", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
